/* eslint-disable */
require('./calendar')
require('./call')
require('./car-front')
require('./car-seat')
require('./car-side-front')
require('./meter')
require('./paint-brush')
require('./quote-left')
require('./quote-right')
require('./search-car')
require('./shield')
require('./transmission')
require('./two-cars')
require('./user-formal')
