/* eslint-disable */
require('./product-bump-square')
require('./product-bump')
require('./product-combo-square')
require('./product-combo')
require('./product-featured-square')
require('./product-featured')
require('./product-highlight-square')
require('./product-highlight')
require('./product-hotdeal-square')
require('./product-hotdeal')
require('./product-showcase-square')
require('./product-showcase')
require('./product-trusted-outline')
require('./product-trusted')
require('./product-video-square')
require('./product-video')
