/* eslint-disable */
require('./apps')
require('./arrow-down')
require('./arrow-left')
require('./arrow-right')
require('./arrow-up')
require('./caret-down')
require('./caret-up')
require('./chevron-down')
require('./chevron-left')
require('./chevron-right')
require('./chevron-up')
require('./menu')
require('./more-alt')
require('./more')
